@startuml
!pragma layout smetana

!include ../diagrams/diagram.styles.puml


agent Participant
agent ParticipantAgent
agent CI as "Credential\nIssuer"
agent IDP as "Identity\nProvider"
agent Dataspace
agent DataspaceAuthority as "Dataspace\nAuthority"
agent Registry as "Dataspace\nRegistry"

DataspaceAuthority -down-> Dataspace  : manages

Dataspace -down-> Registry: uses

Participant -up-> Dataspace : member of
Participant -down-> ParticipantAgent : controls

ParticipantAgent --> Registry : registers/uses

IDP --> ParticipantAgent : issues
ParticipantAgent --> IDP : verifies

CI --> ParticipantAgent : issues
ParticipantAgent --> CI : verifies




@enduml
