@startuml "hub-request-processing"
!pragma layout smetana

!include ../diagrams/diagram.styles.puml

hide empty description

state CONSUMER_REQUESTED: <color:$darkGray>ContractRequestMessage
state PROVIDER_OFFERED: <color:$darkGray>ContractOfferMessage
state CONSUMER_OFFERED: <color:$darkGray>ContractOfferMessage
state CONSUMER_AGREED: <color:$darkGray>ContractOfferEventMessage:accepted
state PROVIDER_AGREED: <color:$darkGray>ContractAgreementMessage
state CONSUMER_VERIFIED: <color:$darkGray>ContractAgreementVerificationMessage
state PROVIDER_FINALIZED: <color:$darkGray>ContractAgreementFinalizationMessage
state DECLINED:  <color:$darkGray>ContractOfferEventMessage:declined

state ERRORED $lightRed #$borderRed : <color:$darkGray>ErrorMessage
state CANCELLED $lightRed #$borderRed:  <color:$darkGray>CancelMessage

[*] --> CONSUMER_REQUESTED: C
CONSUMER_REQUESTED -->  PROVIDER_OFFERED: P
CONSUMER_REQUESTED -->  DECLINED: P

PROVIDER_OFFERED -->  CONSUMER_OFFERED: C
PROVIDER_OFFERED -->  CONSUMER_AGREED: C
PROVIDER_OFFERED -->  DECLINED: C

CONSUMER_OFFERED -->  PROVIDER_OFFERED: P
CONSUMER_OFFERED -->  DECLINED: P
CONSUMER_OFFERED -->  PROVIDER_AGREED: P

CONSUMER_AGREED --> PROVIDER_AGREED: P
CONSUMER_AGREED --> DECLINED: P

PROVIDER_AGREED --> CONSUMER_VERIFIED: C

CONSUMER_VERIFIED --> PROVIDER_FINALIZED: P

PROVIDER_FINALIZED -->[*]
ERRORED --> [*]
CANCELLED --> [*]
DECLINED --> [*]

@enduml
